### ISSUE TITLE
undefined method `sequenced_options' for #<Class:0xde76744>

### ISSUE THREAD

**Issue by ngelx** [derrickreimer/sequenced#27]
Hi,nice work with this gem!

i'm having an issue when trying to save a new sequenced object.

`undefined method 'sequenced_options' for #<Class:0xde76744>`

Not sure what is going on, in my models got something like

```
class Question < ActiveRecord::Base
  has_many :answers
end

class Answer < ActiveRecord::Base
  belongs_to :question
  acts_as_sequenced scope: :question_id
end
```

And in some point in the controller i'm doing 

```
new_a = question.answers.new(answer_params)
if (new_a.save)  <-- here the error is thrown
  ...
end
```

Any help will much appreciated. 
Thanks,

**Comment by djreimer** [comment]
Hey @ngelx, which version of rails are you using? Can you provide a full stack trace?

**Comment by ngelx** [comment]
Hey, sorry for the delay! i've switched to another project and never saw this notification.
the rails version is 4.2 and here is the stack trace as you requested. Any other info needed please let me know, i will keep an eye on notification this time ;) 

```
NoMethodError: undefined method `sequenced_options' for #<Class:0xd2446ec>
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/sequenced-3.1.1/lib/sequenced/acts_as_sequenced.rb:68:in `set_sequential_ids'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:164:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:164:in `block in halting'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `block in call'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5.1/lib/active_record/callbacks.rb:302:in `create_or_update'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:120:in `save'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:37:in `save'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
... 11 levels...
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
        from /vagrant/inflowlive/bin/rails:8:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/vagrant/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
        from /home/vagrant/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

**Comment by ngelx** [comment]
I think i got it. The problem is that my app has some no standard inheritance, and that is breaking the sequenced. 

I'm using a Gem, and extending a model of that gem using inheritance. So the gem got a model `GemX::Aa` and my model is:

```
class Aa < GemX::Aa
   belongs_to :b
   acts_as_sequenced scope: :b_id
    ...
end
```

So, when i try to Save a model "Aa", the error raises.

```
new_aa = b.aas.new()
new_aa.save

NoMethodError: undefined method `sequenced_options' for #<Class:0xd2446ec>
```
